---
- name: Terminate an EC2 instance
  hosts: localhost
  connection: local
  tasks:
    - name: terminating old instances
        module: ec2
        state: 'absent'
        instance_ids: "{{ ansible_ec2_instance_id }}"
