---
- name: terminate old instances
  hosts: all
  tasks:
    - action: ec2_facts
    - name: terminating old instances
      local_action:
        module: ec2
        state: 'absent'
        region: eu-west-1
        key_name: id_rsa-demo
        instance_ids: "{{ ansible_ec2_instance_id }}"
