- name: "HIGH | V-38462 | AUDIT | The RPM package management tool must cryptographically verify the authenticity of all software packages during installation"
  command: grep nosignature /etc/rpmrc /usr/lib/rpm/rpmrc /usr/lib/rpm/redhat/rpmrc ~root/.rpmrc
  register: rpm_sig_audit
  failed_when: rpm_sig_audit.stdout_lines|length > 0
  always_run: yes
  changed_when: no
  ignore_errors: yes

- name: "HIGH | V-38462 | PATCH | The RPM package management tool must cryptographically verify the authenticity of all software packages during installation"
  lineinfile:
      state: absent
      dest: "{{ item }}"
      regexp: nosignature
  ignore_errors: yes
  with_items:
      - /etc/rpmrc
      - /usr/lib/rpm/rpmrc
      - /usr/lib/rpm/redhat/rpmrc
      - ~root/.rpmrc

- name: "HIGH | V-38476 | AUDIT | Vendor-provided cryptographic certificates must be installed to verify the integrity of system software"
  command: rpm -q gpg-pubkey
  register: rpm_key_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes

- name: "HIGH | V-38491 | PATCH | There must be no hosts.equiv on the system"
  file:
      state: absent
      dest: /etc/hosts.equiv

- name: "HIGH | V-38497 | AUDIT | The system must not have accounts configured with blank or null passwords"
  command: grep nullok /etc/pam.d/system-auth
  changed_when: false
  always_run: yes
  ignore_errors: yes
  register: nullok_audit
  failed_when: nullok_audit.stdout_lines|length > 0

- name: "HIGH | V-38497 | PATCH | The system must not have accounts configured with blank or null passwords"
  replace:
      dest: /etc/pam.d/system-auth
      regexp: nullok

- name: "HIGH | V-38607 | PATCH | The SSH daemon must be configured to use only the SSHv2 protocol"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?Protocol \d'
      line: 'Protocol 2'
  notify: restart ssh

- name: "HIGH | V-38614 | PATCH | The SSH daemon must not allow authentication using an empty password"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
  tags:
      - ssh
      - high
      - cat1
      - V-38614
      - ssh

- name: Check ansible version
  fail:
      msg: You must use ansible 2.1 or greater
  when: not ansible_version.full | version_compare('2.1', '>=')
  tags:
      - always

