- name: Check OS version and family
  fail:
      msg: "This role can only be run agaist RHEL 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version | version_compare('7', '!=')

- name: "HIGH | V-38462 | AUDIT | The RPM package management tool must cryptographically verify the authenticity of all software packages during installation"
  command: grep nosignature /etc/rpmrc /usr/lib/rpm/rpmrc /usr/lib/rpm/redhat/rpmrc ~root/.rpmrc
  register: rpm_sig_audit
  failed_when: rpm_sig_audit.stdout_lines|length > 0
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - V-38462
      - rpm
      - audit
      - packages

- name: "HIGH | V-38462 | PATCH | The RPM package management tool must cryptographically verify the authenticity of all software packages during installation"
  lineinfile:
      state: absent
      dest: "{{ item }}"
      regexp: nosignature
  ignore_errors: yes
  with_items:
      - /etc/rpmrc
      - /usr/lib/rpm/rpmrc
      - /usr/lib/rpm/redhat/rpmrc
      - ~root/.rpmrc
  tags:
      - cat1
      - V-38462
      - rpm
      - packages
      - patch

- name: "HIGH | V-38476 | AUDIT | Vendor-provided cryptographic certificates must be installed to verify the integrity of system software"
  command: rpm -q gpg-pubkey
  register: rpm_key_audit
  always_run: yes
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - V-38476
      - rpm
      - audit

- name: "HIGH | V-38476 | PATCH | Vendor-provided cryptographic certificates must be installed to verify the integrity of system software"
  rpm_key:
      state: present
      key: "{{ gpg_key_url }}"
  tags:
      - cat1
      - high
      - V-38476
      - rpm
      - patch

- name: "HIGH | V-38491 | AUDIT | There must be no hosts.equiv on the system"
  stat:
      path: /etc/hosts.equiv
  register: hosts_equiv_audit
  always_run: yes
  ignore_errors: yes
  tags:
      - cat1
      - high
      - V-38491
      - hosts_equiv
      - audit

- name: "HIGH | V-38491 | PATCH | There must be no hosts.equiv on the system"
  file:
      state: absent
      dest: /etc/hosts.equiv
  tags:
      - cat1
      - high
      - V-38491
      - hosts_equiv
      - patch

- name: "HIGH | V-38491 | AUDIT | There must be no .rhosts files on the system"
  stat:
      path: ~{{ item }}/.rhosts
  register: rhosts_audit
  always_run: yes
  with_items: users.stdout_lines
  ignore_errors: True
  failed_when: "rhosts_audit.stat.exists is defined and rhosts_audit.stat.exists == True"
  tags:
      - cat1
      - high
      - V-38491
      - hosts_equiv
      - audit

- name: "HIGH | V-38491 | PATCH | There must be no .rhosts files on the system"
  file:
    state: absent
    dest: ~{{ item }}/.rhosts
  with_items: users.stdout_lines
  tags:
      - cat1
      - high
      - V-38491
      - rhosts
      - patch

- name: "HIGH | V-38497 | AUDIT | The system must not have accounts configured with blank or null passwords"
  command: grep nullok /etc/pam.d/system-auth
  changed_when: false
  always_run: yes
  ignore_errors: yes
  register: nullok_audit
  failed_when: nullok_audit.stdout_lines|length > 0
  tags:
      - cat1
      - high
      - V-38497
      - passwords
      - audit

- name: "HIGH | V-38497 | PATCH | The system must not have accounts configured with blank or null passwords"
  replace:
      dest: /etc/pam.d/system-auth
      regexp: nullok
  tags:
      - cat1
      - high
      - V-38497
      - passwords
      - patch

- name: "HIGH | V-38587 | AUDIT | The telnet-server package must not be installed"
  command: rpm -q telnet-server
  ignore_errors: yes
  always_run: yes
  changed_when: no
  register: telnet_server_audit
  failed_when: "'is not installed' not in telnet_server_audit.stdout"
  tags:
      - cat1
      - high
      - V-38587
      - telnet
      - unsecure_services
      - audit

- name: "HIGH | V-38587 | PATCH | The telnet-server package must not be installed"
  yum:
    name: telnet-server
    state: absent
  tags:
      - cat1
      - high
      - V-38587
      - telnet
      - unsecure_services
      - patch

- name: "HIGH | V-38589 | AUDIT | The telnet daemon must not be running"
  command: chkconfig 'telnet' --list
  register: telnet_service_audit
  failed_when: "'No such file or directory' not in telnet_service_audit.stderr"
  changed_when: false
  always_run: yes
  ignore_errors: yes
  tags:
      - cat1
      - high
      - V-38589
      - telnet
      - unsecure_services
      - audit

- name: "HIGH | V-38589 | PATCH | The telnet daemon must not be running"
  service:
    name: telnet
    state: stopped
    enabled: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - V-38589
      - telnet
      - unsecure_services
      - patch

- name: "HIGH | V-38591 | AUDIT | The rsh-server package must not be installed"
  command: rpm -q rsh-server
  always_run: yes
  register: rsh_server_audit
  failed_when: "'is not installed' not in rsh_server_audit.stdout"
  changed_when: no
  ignore_errors: yes
  tags:
    - cat1
    - high
    - V-38591
    - rsh
    - unsecure_services
    - audit

- name: "HIGH | V-38591 | PATCH | The rsh-server package must not be installed"
  yum:
    name: rsh-server
    state: absent
  tags:
      - cat1
      - high
      - V-38591
      - rsh
      - unsecure_services
      - patch

- name: "HIGH | V-38594 | AUDIT | The rshd service must not be running"
  command: chkconfig 'rsh' --list
  register: rsh_service_audit
  failed_when: "'No such file or directory' not in rsh_service_audit.stderr"
  changed_when: false
  always_run: yes
  ignore_errors: yes
  tags:
      - cat1
      - high
      - V-38594
      - rsh
      - rlogin
      - unsecure_services
      - audit

- name: "HIGH | V-38594 | PATCH | The rshd service must not be running"
  service:
    name: rsh
    state: stopped
    enabled: no
  tags:
      - cat1
      - high
      - V-38594
      - rsh
      - unsecure_services
      - patch

- name: "HIGH | V-38598 | AUDIT | The rexecd service must not be running"
  command: chkconfig 'rexec' --list
  ignore_errors: yes
  register: rexec_status_audit
  failed_when: "'No such file or directory' not in rexec_status_audit.stderr"
  always_run: yes
  changed_when: no
  tags:
      - cat1
      - high
      - V-38598
      - rexec
      - audit

- name: "HIGH | V-38598 | PATCH | The rexecd service must not be running"
  service:
      name: rexec
      state: stopped
  tags:
      - cat1
      - high
      - V-38598
      - rexec
      - patch

- name: "HIGH | V-38602 | AUDIT | The rlogind service must not be running"
  command: chkconfig 'rlogin' --list
  ignore_errors: yes
  register: rlogin_status_audit
  failed_when: "'No such file or directory' not in rlogin_status_audit.stderr"
  always_run: yes
  changed_when: no
  tags:
      - cat1
      - high
      - V-38602
      - rlogin
      - audit

- name: "HIGH | V-38602 | PATCH | The rlogind service must not be running"
  service:
    name: rlogin
    enabled: no
  tags:
      - cat1
      - high
      - V-38602
      - rlogin
      - patch

- name: "HIGH | V-38607 | AUDIT | The SSH daemon must be configured to use only the SSHv2 protocol"
  command: grep "Protocol 2" /etc/ssh/sshd_config
  register: proto2_audit
  ignore_errors: yes
  always_run: yes
  changed_when: no
  tags:
      - cat1
      - high
      - V-38607
      - ssh
      - audit

- name: "HIGH | V-38607 | PATCH | The SSH daemon must be configured to use only the SSHv2 protocol"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?Protocol \d'
      line: 'Protocol 2'
  notify: restart ssh
  tags:
      - high
      - cat1
      - V-38607
      - ssh
      - patch

- name: "HIGH | V-38614 | AUDIT | The SSH daemon must not allow authentication using an empty password"
  command: grep "PermitEmptyPasswords yes" /etc/ssh/sshd_config
  ignore_errors: yes
  always_run: yes
  changed_when: false
  register: ssh_empty_pass_audit
  failed_when: ssh_empty_pass_audit.stdout_lines|length > 0
  tags:
      - high
      - cat1
      - ssh
      - audit
      - V-38614

- name: "HIGH | V-38614 | PATCH | The SSH daemon must not allow authentication using an empty password"
  lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^(#)?PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
  tags:
      - ssh
      - high
      - cat1
      - V-38614
      - ssh

- name: "HIGH | V-38653 | AUDIT | The snmpd service must not use a default password"
  shell: grep -v "^#" /etc/snmp/snmpd.conf| grep public
  register: snmpd_audit
  failed_when: snmpd_audit.stdout_lines|length > 0
  always_run: yes
  when: snmpconf_test.stat.exists
  changed_when: no
  ignore_errors: yes
  tags:
      - cat1
      - high
      - V-38653
      - snmp
      - always

- name: "HIGH | V-38653 | PATCH | The snmpd service must not use a default password"
  replace:
      backup: yes
      dest: /etc/snmp/snmpd.conf
      regexp: (^com2sec.*default\s+)public
      replace: \1{{ cent7stig_snmp_community }}
  when: snmpconf_test.stat.exists and snmpd_audit.stdout != []
  notify: restart snmpd
  tags:
      - cat1
      - high
      - V-38653
      - snmp
      - patch

# V-38666 checks can be found in not_automated.yml

- name: "HIGH | V-38668 | AUDIT | The x86 Ctrl-Alt-Delete key sequence must be disabled"
  stat:
      path: /usr/lib/systemd/system/ctrl-alt-del.target
  register: ctrl_alt_del_audit
  always_run: yes
  changed_when: no
  failed_when: "ctrl_alt_del_audit.stat.islnk is defined and ctrl_alt_del_audit.stat.islnk == False or ctrl_alt_del_audit.stat.lnk_source != '/dev/null'"
  ignore_errors: yes
  tags:
      - V-38668
      - high
      - cat1
      - audit
      - ctrl_alt_delete

- name: "HIGH | V-38668 | PATCH | The x86 Ctrl-Alt-Delete key sequence must be disabled"
  file:
      dest: /usr/lib/systemd/system/ctrl-alt-del.target
      src: /dev/null
      state: link
  tags:
      - high
      - cat1
      - V-38668
      - ctrl_alt_delete
      - patch
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.1 or greater
  when: not ansible_version.full | version_compare('2.1', '>=')
  tags:
      - always

